---
- name: Download iojs
  get_url: url=https://iojs.org/dist/v1.6.4/iojs-v1.6.4-linux-x64.tar.gz dest=/opt/iojs-v1.6.4-linux-x64.tar.gz

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/iojs-v1.6.4-linux-x64.tar.gz -C /opt/

- name: Symlink iojs
  file: src=/opt/iojs-v1.6.4-linux-x64/bin/iojs path=/usr/bin/iojs state=link

- name: Symlink node
  file: src=/opt/iojs-v1.6.4-linux-x64/bin/node path=/usr/bin/node state=link

- name: Symlink npm
  file: src=/opt/iojs-v1.6.4-linux-x64/bin/npm path=/usr/bin/npm state=link

- name: Install yeoman generators
  shell: npm install -g yo grunt-cli bower generator-aspnet 