---
- name: update apt repositories
  apt: update_cache=yes cache_valid_time=3600

- name: common packages
  apt: pkg={{ item }} state=latest
  with_items:
    - git
    - curl
    - gyp
    - build-essential