---
- name: add apt-key for mono
  apt_key: keyserver=keyserver.ubuntu.com id=3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: add 
  lineinfile: dest=/etc/apt/sources.list.d/mono-xamarin.list line="deb http://download.mono-project.com/repo/debian wheezy main" create=yes

- name: update apt repositories
  apt: update_cache=yes cache_valid_time=3600

- name: install mono
  apt: pkg={{ item }} state=present
  with_items:
    - mono-devel
    - mono-complete
